# Generated by Django 4.2.2 on 2023-09-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_itemtable_stockrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtable',
            old_name='stockrate',
            new_name='stock_rate',
        ),
    ]
