# Generated by Django 4.2.2 on 2023-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_itemtable_stock_rate_itemtable_stockrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='stock_rate',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
