# Generated by Django 4.2.2 on 2023-09-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_itemtable_stock_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='stockrate',
        ),
    ]
