# Generated by Django 4.2.2 on 2023-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_itemtable_stockrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='stock_rate',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
