# Generated by Django 4.2.2 on 2023-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_itemtable_stock_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='stock_rate',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
