# Generated by Django 4.2.2 on 2023-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='stock_rate',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
