# Generated by Django 4.2.2 on 2023-10-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_holidays_end_date_remove_holidays_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='holidays',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
